apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbos-app
  template:
    metadata:
      labels:
        app: dbos-app
    spec:
      containers:
        - name: dbos-app
          image: YOUR_ECR_REPO.dkr.ecr.YOUR_REGION.amazonaws.com/YOUR_REPO:kubernetes-integration-latest
          env:
            - name: DBOS_SYSTEM_DATABASE_URL
              value: postgres://postgres:dbos@postgres:5432/kube
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dbos-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-XXXXX,subnet-YYYYY"
spec:
  type: LoadBalancer
  selector:
    app: dbos-app
  ports:
    - port: 8000
      targetPort: 8000
